### ISSUE TITLE
Unable to fetch data from AWS Dynamo DB

### ISSUE THREAD

**Issue by mechingineer** [jcabi/jcabi-dynamo#101]
I am getting this error message:

Caused by: com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: J1U8P1K6QL2R77A1KD6BTB9LVBVV4KQNSO5AEMVJF66Q9ASUAAJG)

PFB my code:

public static void dynamo() throws IOException
   {
	   Credentials credentials = new Credentials.Simple("<MyAccessKey>", "<MySecretKey>");
	    Region region = new Region.Simple(credentials);
	    Table table = region.table("foo");
	    Collection<com.jcabi.dynamo.Item> items = table.frame().where("id", Conditions.equalTo(123));
	    for (com.jcabi.dynamo.Item item : items) {
	      System.out.println(item.get("name").getS());
	    }
   }

Please help me resolve this issue.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@mechingineer[/z](https://www.0crat.com/u/mechingineer) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@mechingineer I believe, the problem is related to the wrong security token you are using. Just make sure you use the right one.
