### ISSUE TITLE
GT and LT operators are not supported by H2Data

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-dynamo#102]
Let's implement this

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.9`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-dynamo#102` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
