### ISSUE TITLE
Link from documentation points to nowhere

### ISSUE THREAD

**Issue by php-coder** [jcabi/jcabi-dynamo#17]
At page http://dynamo.jcabi.com/ there is a paragraph

>Since version 0.9, it is strongly recommended to use wrappers from com.jcabi.dynamo.retry package

and "com.jcabi.dynamo.retry" there is a link to http://dynamo.jcabi.com/apidocs-0.18.1/com/jcabi/dynamo/retry/index.html But when I open it I get 404 page.

**Comment by dmarkov** [comment]
@cyberone this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by cyberone** [comment]
@dmarkov I don't see a 404 page. Maybe it's not developer's issue. Please reassign.

**Comment by yegor256** [comment]
@dmarkov assign me to this task pls

**Comment by dmarkov** [comment]
> @dmarkov assign me to this task pls

@yegor256 OK, it's yours, please proceed

**Comment by yegor256** [comment]
@php-coder I fixed the typo, see 4e0e9e1 Please close the ticket. Thanks!

**Comment by php-coder** [comment]
Right now there is a link to http://dynamo.jcabi.com/apidocs-0.18.2/com/jcabi/dynamo/retry/index.html and it also leads to 404 error.

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.3`

**Comment by yegor256** [comment]
@php-coder should be fine now, please check

**Comment by php-coder** [comment]
Yes, it's fixed now.

**Comment by dmarkov** [comment]
@yegor256 Many thanks! **30 mins** were added to your account in Transaction ID `000-0d805d2f`... +30 added to your rating, current score is: [+6000](http://www.netbout.com/b/35008?open=rating)
