### ISSUE TITLE
Incomplete documentation of wheher Regions must be shut down

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-dynamo#18]
The current documentation of the Region interface is not complete as it doesn't specify whether or not the region must be shut down after all operations are finished.

**How to fix**

In the header comments of the `com.jcabi.dynamo.Region` describe whether or not code similar to one shown below must be called after all operations have been completed.

```
protected void shutdownAws(final Region region) {
    final AmazonDynamoDB aws = region.aws();

    if (aws != null)
    {
        aws.shutdown();
    }
}
```

**Comment by dmarkov** [comment]
@darkled can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@dpisarenko thanks for this report, I added 15 mins to your account, in transaction `49703973`

**Comment by darkled** [comment]
@dpisarenko changes for this issue were merged, please, check it.

**Comment by dpisarenko** [comment]
@darkled Thanks!

**Comment by dmarkov** [comment]
@darkled I just added **30 mins** to your account, many thanks for your contribution..... +30 added to your rating, at the moment it is: [+210](http://www.netbout.com/b/35091?open=rating)
