### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-dynamo#22]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@nathansgreen please help, the task is yours

**Comment by dmarkov** [comment]
@maurezen many thanks for the report, I topped your account for 15 mins, transaction 49997570

**Comment by nathansgreen** [comment]
@dmarkov @maurezen I created PR #23 but haven't seen any review activity yet. Do I need to do something else?

**Comment by nathansgreen** [comment]
@dmarkov I don't see my login tagged on this issue. Should it be?

**Comment by yegor256** [comment]
@nathansgreen you did everything right, just a wait a bit pls

**Comment by nathansgreen** [comment]
@maurezen PR #23 has been merged. Can you close the issue?

**Comment by dmarkov** [comment]
@nathansgreen thanks, I just added **30 mins** to your account, payment `AP-9LW65171T1722632M`... +30 added to your rating, current score is: [+160](http://www.netbout.com/b/35107?open=rating)
