### ISSUE TITLE
Qulice configuration - no license specified.

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-dynamo#27]
1. Checkout master branch
2. run `mvn qulice:check -Pqulice`
3. There are multiple `Line does not match expected header line of ' * BSD License'. (HeaderCheck)` messages.

This is a known bug of qulice configuration in parent-0.31 (jcabi/jcabi-parent#19), accessed via jcabi-0.16. Suggested action is waiting until jcabi/jcabi#297 fix is released and upgrading jcabi version.

**Comment by yegor256** [comment]
There is no urgent need to upgrade to a new parent

**Comment by maurezen** [comment]
@yegor256 please correct me if I understand this wrong, but are you saying that fixing failing code style checks in master are LESS important than updating a copyright section (issue #22, labeled by you as a valid bug and already fixed)?

**Comment by yegor256** [comment]
@maurezen master is not broken now. `mvn qulice:check -Pqulice` is not a documented operation. this one is documented (and used by Rultor and Travis): `mvn clean install -Pqulice`.

**Comment by maurezen** [comment]
@yegor256 I must remind that `mvn -Pqulice` executes `check` goal of `qulice-maven-plugin`. Running `mvn clean install -Pqulice` resulted in the same `HeaderCheck` failures for jcabi-dynamo, so the issue is still here. Should I double-check for another jcabi descendants?

**Comment by yegor256** [comment]
Try to run `mvn clean install -Pqulice` in this project and post your log here if it fails.

**Comment by maurezen** [comment]
Relevant log part:
>[INFO] --- qulice-maven-plugin:0.10:check (default) @ jcabi-dynamo ---
>[INFO] LICENSE found: file:D:/maurezen/programs/odesk/yegor256/jcabi-dynamo/LICENSE.txt
>[ERROR] \src\main\java\com\jcabi\dynamo\Attributes.java[3]: Line does not match expected header line of ' *'. (HeaderCheck)

Please tell me if you need full build log - and if yes, please tell me if there is preferrable method of attaching 200+kb log.

**Comment by yegor256** [comment]
@maurezen how do you run it? what is your environment? at the moment both Travis (Ubuntu) and Appveyor (Windows) show clean build..

**Comment by maurezen** [comment]
@yegor256 win7x64, maven 3.2.5 running under java 1.7.0-21, checked out master branch from maurezen/jcabi-dynamo (which is at the moment even with master of jcabi/jcabi-dynamo).

**Comment by maurezen** [comment]
@yegor256 any comments?

**Comment by yegor256** [comment]
@maurezen first, I can't reproduce it. both Travis and Appveyor are showing clean build. second, even if it's reproducible in some environment, it's not worth a full bug, see http://www.teamed.io/policy.html#13

**Comment by maurezen** [comment]
@yegor256 we still need to determine if there is a problem - to fix it if there is one. So if the build fails under _some_ environment, it is okay? As long as this is not the build server environment?
