### ISSUE TITLE
H2Data does not support COLUMNS with ".", "-", or digits

### ISSUE THREAD

**Issue by pinaf** [jcabi/jcabi-dynamo#28]
Fix for issue #7 only dealt with table names. The same Base32 encoding should be done for column names. This is needed for [yegor/s3auth#90](https://github.com/yegor256/s3auth/issues/90)

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@pinaf many thanks for the bug report, I added 15 mins to your acc, transaction `AP-3LH50245RL416922R`

**Comment by pinaf** [comment]
@dmarkov thank you

**Comment by dmarkov** [comment]
@apocarteres the task is yours

**Comment by apocarteres** [comment]
@dmarkov i have added test to prove the issue, also added puzzle there. Please find someone to work on that puzzle.

**Comment by apocarteres** [comment]
@yegor256 what do you think about PR with test and puzzle for this issue? I think it's out of issue's scope to make a decision should H2Data support mentioned functionality or not, moreover to add/remove such functionality.

**Comment by pinaf** [comment]
@apocarteres We need class `H2Data` to support such functionality - it currently does not. If you look at issue #7 you'll see the solution was to use Base32 encoding. However #7 only did this for table names. In this issue we need it for column names also.

**Comment by apocarteres** [comment]
@pinaf i see, let me discuss it with Yegor, please

**Comment by apocarteres** [comment]
@dmarkov it's needed more time here

**Comment by pinaf** [comment]
@apocarteres any progress?

**Comment by dmarkov** [comment]
> @dmarkov it's needed more time here

@apocarteres agreed, take your time

**Comment by apocarteres** [comment]
@pinaf waiting for @yegor256 comments

**Comment by yegor256** [comment]
@apocarteres sure, reproducing a problem is a good solution. check this article: http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by apocarteres** [comment]
@yegor256 ok thanks
@pinaf well, i have created PR with test to prove that <code>H2Data</code> doesn't support such symbols you mentioned above. Also the puzzle created with ask to implement such functions if they should be implemented. I think the next step is guys make new task to solve the puzzle and add requested features then.

**Comment by pinaf** [comment]
@apocarteres ok, let's get it to pass the code review :)

**Comment by apocarteres** [comment]
https://github.com/pinaf test added and merged. please check

**Comment by pinaf** [comment]
@apocarteres thanks!

**Comment by dmarkov** [comment]
@apocarteres **30 mins** was added to your account, many thanks for your contribution!; +30 to your rating, your total score is [+255](http://www.netbout.com/b/35111?open=rating)

**Comment by longtimeago** [comment]
@yegor256 looks like we need to release new version of jcabi-dynamo to proceed with yegor/s3auth#90

**Comment by pinaf** [comment]
@longtimeago also the functionality isn't there yet.

**Comment by longtimeago** [comment]
@pinaf ahr .... still blocked :(

**Comment by 0pdd** [comment]
@pinaf the only puzzle [#97](https://github.com/jcabi/jcabi-dynamo/issues/97) is solved here.
