### ISSUE TITLE
"JSR-303 validator failed to initialize" warning during the build.

### ISSUE THREAD

**Issue by nhekfqn** [jcabi/jcabi-dynamo#31]
During maven build following warning reported:

[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)

**Comment by yegor256** [comment]
it's just a warning, not really a bug
