### ISSUE TITLE
MkTable.java:106-107: Implement MkTable.delete() operation. delete() method...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-dynamo#35]
Puzzle `8-abdd4627` in `src/main/java/com/jcabi/dynamo/mock/MkTable.java:106-107` has to be resolved: Implement MkTable.delete() operation. delete() method added to Table interface and implemented in AwsTable class so far.... The puzzle was created by Nikolay Popov on 28-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@nhekfqn the task is yours please proceed

**Comment by dmarkov** [comment]
@yamstranger the issue is yours, please help

**Comment by YamStranger** [comment]
@dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger -30 points to your rating

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger I will try to find someone else

**Comment by dmarkov** [comment]
@tousifkhan please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@tousifkhan you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). do not forget that you should remove the `@todo` puzzle from the source code. -30 added to your rating, at the moment it is: [-210](http://www.netbout.com/b/35305?open=rating)

**Comment by dmarkov** [comment]
@suseika the task is yours please proceed

**Comment by Suseika** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@suseika sure, thanks for telling me, take your time

**Comment by Suseika** [comment]
@dmarkov Fixed in #50

**Comment by dmarkov** [comment]
@rultor rultor closed it (automatically), @dmarkov please take a look

**Comment by dmarkov** [comment]
@yegor256 We are done here, thanks all

**Comment by dmarkov** [comment]
@suseika **30 mins** was added to your account, many thanks for your contribution (payment AP-6G388493XC298292C)! The task took 504 hours and 38 mins.; +30 added to your rating, at the moment it is: [+578](http://www.netbout.com/b/35381?open=rating)
