### ISSUE TITLE
ReTable.java:101-102: Implement ReTable.delete() operation. delete() method...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-dynamo#36]
Puzzle `8-81cf3845` in `src/main/java/com/jcabi/dynamo/retry/ReTable.java:101-102` has to be resolved: Implement ReTable.delete() operation. delete() method added to Table interface and implemented in AwsTable class so far.... The puzzle was created by Nikolay Popov on 28-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@apocarteres it's in your hands now, please proceed

**Comment by dmarkov** [comment]
@super132 please proceed, it's yours

**Comment by super132** [comment]
@dmarkov , PR #41 fixed this issue. Would you please close this ticket? Thanks.

**Comment by super132** [comment]
@nhekfqn , the puzzle is fixed by PR #41 , would you please close this ticket? Thanks

**Comment by super132** [comment]
@dmarkov could you please close this ticket? Thanks.

**Comment by super132** [comment]
@dmarkov could you please close this ticket as this is a puzzle and need to be closed by you. Thanks.

**Comment by dmarkov** [comment]
@yegor256 Thanks all, closed

**Comment by dmarkov** [comment]
@super132 paid, thanks, added **30 mins** to your account, payment `AP-7JT71079BA035134P`, 170 hours and 24 mins was spent. +30 added to your rating, current score is: [+241](http://www.netbout.com/b/35282?open=rating)
