### ISSUE TITLE
Build failed on windows with lots of EOL violations

### ISSUE THREAD

**Issue by YamStranger** [jcabi/jcabi-dynamo#42]
@dmarkov Looks like we need to add .gitattributes to force EOL of the repo.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@YamStranger fixed already in https://github.com/jcabi/jcabi-dynamo/commit/2797b4f8a91b54956a48c2d76477df061fb7f249 thanks
