### ISSUE TITLE
H2DataTest doesn't use update method of MkData interface

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-dynamo#48]
`MkData#update` method is not covered by `H2DataTest` unit test, and it should be.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by dmarkov** [comment]
@super132 the task is yours (budget is 30 mins)

**Comment by dmarkov** [comment]
@suseika thanks for the report, I topped your acc for 15 mins, payment ID `AP-1DT02337V2313784N`

**Comment by super132** [comment]
@Suseika PR #51 fixes this issue. Please close this ticket. Thanks.

**Comment by dmarkov** [comment]
@super132 Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-4JH07221GX367560K`, the task took 95 hours and 19 mins)

+30 added to your rating, at the moment it is: [+841](http://www.netbout.com/b/35282?open=rating)
