### ISSUE TITLE
`String table` parameter in MkData methods doesn't make sense

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-dynamo#49]
`MkData` represents data of a table. Conceptually it is wrong to require table's name to search for data in an object that represents the data of a table, because table name should not matter. But each of `MkData` methods requires a table name as a parameter. Clients of MkData are not supposed to know the name of the table, because there is no table — only its records.

Now, I see why that parameter is in the methods' signatures in the first place: it is the implementation of `H2Data` leaking into the `MkData` interface's signature. `H2Data` does need the name of a table. But nevertheless the name of a table should not be a parameter of `MkData` methods, but instead a constructor parameter in `H2Data`.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by dmarkov** [comment]
@super132 it's yours, budget is 30 mins, please go ahead

**Comment by dmarkov** [comment]
@suseika thanks for reporting! I topped your account for 15 mins, transaction AP-7B600112YF3310800

**Comment by super132** [comment]
@Suseika I think the assumption here with `MkData` represents data of a table is wrong may be? From the code, the design of `MkData` should represent a *database* instead of a table. There is a `Table` interface which represents a table instead. Does it make sense to you? Thanks.

**Comment by Suseika** [comment]
@super132 `MkData` doesn't represent a database, if by database you mean something we connect to and not just a generalized data storage. And I didn't mean that `MkData` currently represents a table. `MkData` represents relational data without the notion of it being in a table or anywhere else (that's why `table` parameter in `MkData` methods is redundant).

**Comment by super132** [comment]
@Suseika I think I understand what you mean here. You're proposing that `MkData` should represent data of a table instead of data of a collection of tables. I will revise the codes here to make it behave like this. Thanks.

**Comment by super132** [comment]
@dmarkov Please review PR #52. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov Please review PR #52. Thanks.

@super132 will take a look, thanks

**Comment by yegor256** [comment]
@Suseika @super132 I think we're doing something wrong here... how about this code:

```java
        final Region region = new MkRegion(
            new H2Data()
              .with("alpha", new String[] {"key"}, new String[] {"attr"})
              .with("beta", new String[] {"key"}, new String[] {"attr"})
        );
        region.table("alpha").put(
            new Attributes()
                .with("key", "32443")
                .with("attr", new AttributeValue("some\n\t\u20ac text"))
        );
        MatcherAssert.assertThat(
            region.table("beta").frame(),
            Matchers.emptyIterable()
        );
```

It has to work, but after that pull request it will fail. Or I'm wrong?

**Comment by super132** [comment]
@dmarkov need more time here.

**Comment by super132** [comment]
@yegor256 By definition of this ticket now, `H2Data` is no longer represents a collection of table but the underlying implementation of data store of **a Table**. Therefore, `H2Data.with` no longer work this way and no extra table is created. Do you agree on this design?

If yes, to achieve what we could do in the codes above, I think we need to change the constructor of `MkRegion` to accept an iterable of `MkData` instead. Extend `MkData` to return table name and create a map associated the table name to `MkData` inside `MkRegion` to achieve this purpose. Would you please share your opinion on it? Thanks.

**Comment by yegor256** [comment]
@super132 I think that the ticket is wrong in general and should be closed (you will be paid anyway). Let's wait for @Suseika opinion

**Comment by dmarkov** [comment]
> @dmarkov need more time here.

@super132 no problem, thanks for letting me know

**Comment by Suseika** [comment]
@yegor256 Okay, let's close it.

**Comment by yegor256** [comment]
@Suseika do you agree with my argument?

**Comment by Suseika** [comment]
@yegor256 Yeah, I misunderstood the purpose of `MkData` interface, my bad. Let's close this issue.

**Comment by super132** [comment]
@Suseika Please kindly close the ticket as it can only be closed by reporter. Thanks.

**Comment by yegor256** [comment]
@Suseika yes, indeed, please close it. thanks.

**Comment by dmarkov** [comment]
@super132 Much appreciated! **30 mins** was added to your account, payment ID `AP-14999266A28211604`, time spent is 242 hours and 57 mins... +30 added to your rating, current score is: [+1086](http://www.netbout.com/b/35282?open=rating)
