### ISSUE TITLE
AwsTable#print needs to be extracted in a separate class

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-dynamo#54]
`AwsTable#print` is a pubilc static method that operates on public methods of its argument `ConsumedCapacity`. It could be made into an instance method of `PrintableConsumedCapacity` class, so we have one less public static method in our codebase.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@Suseika good catch, thanks

**Comment by dmarkov** [comment]
@suseika many thanks for the bug report, I added 15 mins to your acc, transaction `AP-87Y22228UH650533B`

**Comment by dmarkov** [comment]
@prondzyn please help, the task is yours

**Comment by prondzyn** [comment]
@dmarkov PR #82 prepared

**Comment by dmarkov** [comment]
> @dmarkov PR #82 prepared

@prondzyn thanks

**Comment by prondzyn** [comment]
@dmarkov need more time. Still waiting on @yegor256 's merge in #82

**Comment by dmarkov** [comment]
> @dmarkov need more time. Still waiting on @yegor256 's merge in #82

@prondzyn agreed, take your time

**Comment by prondzyn** [comment]
@Suseika please close the task

**Comment by dmarkov** [comment]
@prondzyn paid, thanks, added **30 mins** to your account, payment `AP-2RA22125EF354472T`, 407 hours and 19 mins was spent... +30 to your rating, your total score is [+30](http://www.netbout.com/b/35715?open=rating)
