### ISSUE TITLE
AttributeUpdates class does not have any unit tests

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-dynamo#55]
There are plenty of non-trivial methods that are actively used across our codebase, but none of them are tested.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by dmarkov** [comment]
@suseika many thanks for the bug report, I added 15 mins to your acc, transaction `AP-5EA642900D542153G`

**Comment by dmarkov** [comment]
@amihaiemil please help, the task is yours

**Comment by amihaiemil** [comment]
@dmarkov PR #79 is for this

**Comment by dmarkov** [comment]
> @dmarkov PR #79 is for this

@amihaiemil thank you!

**Comment by amihaiemil** [comment]
@Suseika the pr has been merged. Please close this issue.

**Comment by Suseika** [comment]
@amihaiemil Thanks

**Comment by dmarkov** [comment]
@amihaiemil paid, thanks, added **30 mins** to your account, payment `AP-2S314565XT557845H`, 310 hours and 30 mins was spent. added +30 to your rating, now it is equal to [+503](http://www.netbout.com/b/36402?open=rating)
