### ISSUE TITLE
NotNull annotations are inconsistently used

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-dynamo#56]
There are many classes that contain methods whose arguments are annotated with `@NotNull`, and also some methods that don't have those annotations. I'm speaking strictly about methods whose parameters are descendants of `Object`.

For example, `AttributeUpdates#with(String,AttributeValue)` and `AttributeUpdates#with(String,Object)` methods lack `@NotNull` validation for their arguments. Other `AttributeUpdates#with` methods have those annotations for their arguments.

Also, I'm not sure if methods inherited from `Map` that have proper implementations, like `AttributeUpdates#containsKey(Object)` and *unlike* `AttributeUpdates#remove(Object)`, should have their parameters annotated with `@NotNull` as well.

Other examples of inconsistent `@NotNull` usage are: `QueryValve#withSelect(Select)`, `QueryValve#withIndexName(String)`.

<hr id='w'>

 - `56-be65f863`/#64 (by Jose Volmei Dal Pra Junior)
 - `56-9ee1f8fe`/#65 (by )

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@Suseika right, let's make sure we have `NotNull` everywhere

**Comment by dmarkov** [comment]
@suseika thanks for this report, I added 15 mins to your account, in transaction `AP-5CU20142KS901154G`

**Comment by dmarkov** [comment]
@tmjee please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by tmjee** [comment]
@dmarkov fixed in pull request #61

**Comment by dmarkov** [comment]
> @dmarkov fixed in pull request #61 

@tmjee ok thanks

**Comment by dmarkov** [comment]
@suseika these 2 puzzles were created in this ticket: `56-be65f863`/#64, `56-9ee1f8fe`

**Comment by dmarkov** [comment]
@amihaiemil the task is yours please proceed

**Comment by amihaiemil** [comment]
@Suseika The validation api was removed entirely from this project in December 2015 (issue #69, commit 049577d89f405d4ee24ff01388bfb83c9e416b13) . This ticket is not valid anymore, so please close it. Thanks.

**Comment by dmarkov** [comment]
@amihaiemil thank you, added **1 hour** to your acc, payment num is `AP-1V285136TC829420D`, 19 hours and 26 mins spent in total to complete... there is a bonus for fast delivery (m=1166)... +60 added to your rating, current score is: [+300](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@suseika last puzzled solved `56-9ee1f8fe`/#65
