### ISSUE TITLE
Can't retrieve attributes with uppercase letters

### ISSUE THREAD

**Issue by nan-zhong** [jcabi/jcabi-dynamo#57]
Since dynamodb attribute names are case sensitive, what is the reason to convert all attribute name to lowercase in AwsItem and Conditions classes? This makes it impossible to retrieve attributes with uppercase letters in their names. Thanks.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@nan-zhong looks like a bug in the library... let us fix it

**Comment by dmarkov** [comment]
@suseika this is your task now, please help

**Comment by dmarkov** [comment]
@suseika you're holding this task for 15 days already; -30 to your rating, your total score is [+841](http://www.netbout.com/b/35381?open=rating)

**Comment by Suseika** [comment]
@dmarkov Please assign this to someone else

**Comment by dmarkov** [comment]
> @dmarkov Please assign this to someone else

@suseika I deducted 30 points from your rating

**Comment by dmarkov** [comment]
> @dmarkov Please assign this to someone else

@suseika got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@tmjee please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by tmjee** [comment]
@dmarkov presume this is for all attributes which involves 
- Attributes
- AttributesUpdates
and not only AwsItem and Conditions.

**Comment by tmjee** [comment]
@dmarkov fixed in #59

**Comment by dmarkov** [comment]
> @dmarkov presume this is for all attributes which involves 
> - Attributes
> - AttributesUpdates
> 
> and not only AwsItem and Conditions.
> 
> and also that we want to preserve the Locale.
> 

@tmjee address all technical questions to the author of the ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by dmarkov** [comment]
> @dmarkov fixed in #59

@tmjee thanks, we'll review it soon

**Comment by tmjee** [comment]
@dmarkov Can we close this issue please. Thx

**Comment by nan-zhong** [comment]
Thanks for fixing it!

**Comment by dmarkov** [comment]
> @dmarkov Can we close this issue please. Thx

@tmjee you should ask ticket author to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by dmarkov** [comment]
@tmjee I added **30 mins** to your account, many thanks for working with the project! The completion time here was AP-0XV32095YX6507422.; added +30 to your rating, now it is equal to [+75](http://www.netbout.com/b/35603?open=rating)
