### ISSUE TITLE
Is there any advantages compare to official ORM class

### ISSUE THREAD

**Issue by ieiayaobb** [jcabi/jcabi-dynamo#58]
I don't know whether this framework born earlier than the official ORM class.
So can you give more introductions compare to the official ORM class as below:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaORMDynamoDBMapper.html
Thanks a lot

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@ieiayaobb indeed, jcabi-dynamo was created before that ORM class. So, you're free to use either jcabi-dynamo or that ORM module. But keep this in mind: http://www.yegor256.com/2014/12/01/orm-offensive-anti-pattern.html
