### ISSUE TITLE
unused variable in MkFrame#through(Valve)

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-dynamo#63]
While we are at ```com.jcabi.dynamo.mock.MkFrame.through(Valve)```,
shouldn't we ```return this.through(valve);``` instead of the implemented```return this;```?

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@simonjenga not sure I got the idea... what you're suggesting will cause an endless recursion. Or I miss something?

**Comment by simonjenga** [comment]
@yegor256 endless recursion? There needs to be way to make use of the parameter passed in that method. It's not currently being used.

You may also try to ```return new MkFrame(this.data, this.tbl).through(valve);```

**Comment by yegor256** [comment]
@simonjenga ah, I see. But we don't need this param for a mock version of `Frame`. We simply don't care what the `Valve` is, since we always return fast. The "valve" is used in order to optimize the search. We don't need any optimization in the mock.
