### ISSUE TITLE
RegionITCase.java:53-56: integration test fails when adding...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-dynamo#65]
Puzzle `56-9ee1f8fe` in `src/test/java/com/jcabi/dynamo/RegionITCase.java:53-56` has to be resolved: integration test fails when adding @notnull to constraints this needs to be fixed in methods RegionITCase.worksWithAmazon() and RegionITCase.retrievesAttributesFromDynamo(). Also see AwsIteratorITCase.... The puzzle was created by tkjee on 5-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@piddubnyi please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@piddubnyi the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

do not forget that you should remove the `@todo` puzzle from the source code

-30 to your rating, your total score is [-90](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@piddubnyi you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-90](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@nikoladespotoski this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by NikolaDespotoski** [comment]
@dmarkov assign someone else

**Comment by dmarkov** [comment]
> @dmarkov assign someone else

@nikoladespotoski I will ask somebody else to pick this up

**Comment by dmarkov** [comment]
@amihaiemil it's your task, go ahead

**Comment by amihaiemil** [comment]
@dmarkov I created PR #74 for this issue. Please assign a reviewer. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov PR #74 has been merged and closed. Please deploy it and close this issue. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #74 for this issue. Please assign a reviewer. Thanks. 

@amihaiemil OK

**Comment by dmarkov** [comment]
> @dmarkov PR #74 has been merged and closed. Please deploy it and close this issue. Thanks. 

@amihaiemil OK

**Comment by dmarkov** [comment]
@yegor256 Thanks, closing it now.

**Comment by dmarkov** [comment]
@amihaiemil paid, thanks, added **30 mins** to your account, payment `AP-72J92236DR009805V`, 195 hours and 56 mins was spent... +30 to your rating, your total score is [+165](http://www.netbout.com/b/36402?open=rating)
