### ISSUE TITLE
H2Data does not support names with ".", "-", or digits

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-dynamo#7]
I encountered this issue while working on https://github.com/yegor256/s3auth/issues/90.

In S3Auth, the table and attribute names contain `.` characters, e.g. `domain.name`. However, [H2 does not allow this](http://www.h2database.com/html/grammar.html#name), but [http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html](Amazon Dynamo DB) does; Dynamo DB allows `-` characters and digits `0-9` for table names, and attributes can be any UTF-8 character.

This is something that we should take into account, as other users of this library may also be using names that are not allowed by `H2Data` but allowed by Dynamo DB.

**Comment by dmarkov** [comment]
@jenya can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by yegor256** [comment]
@dmarkov please assign someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else

@yegor256 all right, we'll find someone else for this task

**Comment by dmarkov** [comment]
@jenya check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 13 days. If you can't close it within the next 16 hours I'll have to assign someone else to it

-30 added to your rating, current score is: [-75](http://www.netbout.com/b/35092?open=rating)

**Comment by dmarkov** [comment]
@romankisilenko this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by RomanKisilenko** [comment]
@carlosmiranda The PR was revived and closed. Please close this issue.

**Comment by carlosmiranda** [comment]
@RomanKisilenko This has been a long running task, so the resolution is much appreciated! Closing now...

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.2`

**Comment by dmarkov** [comment]
@romankisilenko Thanks a lot, I just topped your account for **30 mins**, transaction ID `50616370`

+30 added to your rating, at the moment it is: +360
