### ISSUE TITLE
Support for deleting items

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-dynamo#8]
We're looking to migrate the S3Auth project to jcabi-dynamo (yegor256/s3auth#90). In jcabi-dynamo, there doesn't appear to be any support for deleting items:

```java
        final AmazonDynamoDB amazon = this.client.get();
        amazon.deleteItem(
            new DeleteItemRequest(
                this.table,
                new ImmutableMap.Builder<String, AttributeValue>()
                    .put(DefaultDynamo.NAME, new AttributeValue(domain.name()))
                    .build()
            )
        );
```

What I end up doing is that I get the `AmazonDynamoDB` instance from `Region`. Can we add support for it in jcabi-dynamo?

**Comment by dmarkov** [comment]
@antacerod please stop working with it, somebody else will pick it up, thanks

stop where you are, the task is not yours any more, thanks!

this ticket is not yours any more, thanks

this task is not yours any more, please stop working with it (or ignore it if you haven't started yet), Thanks!

it's not your task any more, please stop working with it (if you were)

**Comment by dmarkov** [comment]
@pandreev this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@pandreev the task is your hands for the last 13 days.. keep in mind that if it's not closed in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -30 added to your rating, current score is: -90

**Comment by dmarkov** [comment]
@pandreev you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 to your rating, your total score is -210

**Comment by dmarkov** [comment]
@nhekfqn This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by nhekfqn** [comment]
@dmarkov PR https://github.com/jcabi/jcabi-dynamo/pull/29 has been submitted.

Two new tickets submitted (#25 #26) in order to implement new method Table.delete in other classes implementing Table. Puzzles for those tickets added in code.

**Comment by nhekfqn** [comment]
@dmarkov I also mentioned Checkstyle checks cannot be suppressed with @SuppressWarnings annotation, so I submitted another ticket to qulice https://github.com/teamed/qulice/issues/392

**Comment by nhekfqn** [comment]
@dmarkov Related PR has been merged.

**Comment by nhekfqn** [comment]
@carlosmiranda Could you close the ticket please?

**Comment by carlosmiranda** [comment]
@nhekfqn Looks good, thanks! Closing...

**Comment by nhekfqn** [comment]
@dmarkov The ticket has been closed.

**Comment by dmarkov** [comment]
@nhekfqn **30 mins** added to your account (payment number `51004274`), many thanks for your contribution!; +30 added to your rating, current score is: [+135](http://www.netbout.com/b/35123?open=rating)

**Comment by dmarkov** [comment]
2 puzzles were created here: `8-abdd4627`, `8-81cf3845`

**Comment by dmarkov** [comment]
@carlosmiranda the last puzzle `8-abdd4627`/#35 originated from here solved
