### ISSUE TITLE
GSI query

### ISSUE THREAD

**Issue by piotrkot** [jcabi/jcabi-dynamo#83]
Please, provide an example how to make a valid query using GSI (Global Secondary Index).

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by piotrkot** [comment]
@dmarkov @yegor256 I see it takes quite a while to get a response here. Luckily, I found the answer myself.
Assuming we query table, TB, with GSI, INX, where that index has the partition key, IPK. And if we search for IPK value "val", we should call:
```
        region.table("TB").frame().where("IPK", "val").through(
            new QueryValve().withIndexName("INX")
                    .withConsistentRead(false)
        );
```
The most important is that if it does not work you are probably using latest release version 0.21 with the bug #76.
