### ISSUE TITLE
conditional put

### ISSUE THREAD

**Issue by toonsevrin** [jcabi/jcabi-dynamo#86]
Is there a way to conditionally put an item where the condition is checked server side (atomically)?

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@toonsevrin such a thing is not supported by Amazon. The best you can do is to use `ADD`:

```
item.put(
  "total",
  new AttributeValueUpdate().withValue(
    new AttributeValue().withN("5").withAction(AttributeAction.ADD)
  )
);
```

Real example: https://github.com/yegor256/jare/blob/0.7.2/src/main/java/io/jare/dynamo/DyUsage.java#L158-L165

Otherwise, consider using www.stateful.co

**Comment by toonsevrin** [comment]
It would be a cool addition, it's already in dynamodb natively (send update with a parameter condition, for example balance > 20$), so it should not be too hard to add, though quite essential.
