### ISSUE TITLE
Can I use jcabi-dynamo-0.21.4.jar with Android Studio?

### ISSUE THREAD

**Issue by orid123** [jcabi/jcabi-dynamo#87]
Hi
    If yes, is there any example?
Thanks
Ori

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@orid123 I don't see why not. Try it out and report any issues, if you have them
