### ISSUE TITLE
Conditions support equalTo...Any intention to support >, <, >=, <=, between

### ISSUE THREAD

**Issue by hlkn** [jcabi/jcabi-dynamo#89]
Hi Yegor,

Do you intend to support >, <, >=, <=, between in the Conditions

Or 

Is there any workaround?

Thanks and Regards,
Henry

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@hlkn you can do it with AWS Java SDK, just use their classes. There is no reason to re-implement all that in our library.
