### ISSUE TITLE
AwsFrame.isEmpty() is not effective

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-dynamo#96]
It's using `size()`, which runs COUNT. It's not effective.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:jcabi/jcabi-dynamo#96`.

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-dynamo#96` is not in scope.
