### ISSUE TITLE
H2DataTest.java:147-150: <body>H2Data doesn't support...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-dynamo#97]
The puzzle `28-4427f443` from #28 has to be resolved:

https://github.com/jcabi/jcabi-dynamo/blob/13c9a625b0d3bc4eaf6ee810c6c9f79db302c00c/src/test/java/com/jcabi/dynamo/mock/H2DataTest.java#L147-L150

The puzzle was created by Yegor Bugayenko on 24-Dec-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `28-4427f443` has disappeared from the source code, that's why I closed this issue.
